homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include custom.yaml

frontend:
  themes:
    minimal:
      dark-primary-color: "#192231"
      primary-color: "#98878f"
      light-primary-color: "#98878f"
      paper-toggle-button-checked-ink-color: "#494e6b"
      paper-toggle-button-checked-button-color: "#494e6b"
      paper-toggle-button-checked-bar-color: "#494e6b"
      paper-slider-knob-color: "#494e6b"
      paper-slider-knob-start-color: "#494e6b"
      paper-slider-pin-color: "#494e6b"
      paper-slider-active-color: "#494e6b"
    vintage:
      dark-primary-color: "#373f27"
      primary-color: "#636b46"
      light-primary-color: "#e9e7da"
      paper-toggle-button-checked-ink-color: "#cda34f"
      paper-toggle-button-checked-button-color: "#cda34f"
      paper-toggle-button-checked-bar-color: "#cda34f"
      paper-slider-knob-color: "#cda34f"
      paper-slider-knob-start-color: "#cda34f"
      paper-slider-pin-color: "#cda34f"
      paper-slider-active-color: "#cda34f"
    edark:
      dark-primary-color: "#131617"
      primary-color: "#3872a4"
      primary-background-color: "#131617"
      primary-text-color: "#d2d2d2"
      paper-grey-50: "#131617"
      paper-drawer-panel: "#131617"
      paper-listbox-background-color: "#131617"
      light-primary-color: "#3872a4"
      paper-toggle-button-checked-ink-color: "#76323F"
      paper-toggle-button-checked-button-color: "#76323F"
      paper-toggle-button-checked-bar-color: "#76323F"
      paper-slider-knob-color: "#3872a4"
      paper-slider-knob-start-color: "#76323F"
      paper-slider-pin-color: "#76323F"
      paper-slider-active-color: "#76323F"
      paper-slider-secondary-color: "#FFE0B2"


config:

logger:
  default: error
  logs:
    DenonAVR: fatal
#    homeassistant.components.device_tracker.tplink: critical

http:
  api_password: !secret http_pass
  base_url: !secret base_url
  server_port: 8254 
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true

updater:

discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

recorder:
  exclude:
    domains:
      - camera
    entities:
      - sensor.pws_alerts
      - sensor.pws_precip_1d
      - sensor.pws_precip_1d_in
      - sensor.pws_temp_f
      - sensor.pws_temp_high_1d_f
      - sensor.pws_temp_high_record_f
      - sensor.pws_temp_low_1d_f
      - sensor.pws_temp_low_record_f
      - sensor.pws_weather_1d
      - sensor.pws_weather_1n
      - sensor.pws_weather_2d
      - sensor.pws_weather_2n
      - sensor.pws_weather_3d
      - sensor.pws_weather_3n
      - sensor.pws_weather_4d
      - sensor.pws_weather_4n
      - sensor.pws_wind_1d_mph
      - sensor.pws_wind_mph
      - sensor.sunrise_time
      - sensor.sunset_time
      - sensor.exchange_rate_1_btc
      - sensor.ethereum
      - sensor.myipopendnscom

history:
  exclude:
    domains:
      - automation
      - updater
      - sun
      - script
      - group
      - camera
    entities:
      - sensor.pws_alerts
      - sensor.pws_precip_1d
      - sensor.pws_precip_1d_in
      - sensor.pws_temp_f
      - sensor.pws_temp_high_1d_f
      - sensor.pws_temp_high_record_f
      - sensor.pws_temp_low_1d_f
      - sensor.pws_temp_low_record_f
      - sensor.pws_weather_1d
      - sensor.pws_weather_1n
      - sensor.pws_weather_2d
      - sensor.pws_weather_2n
      - sensor.pws_weather_3d
      - sensor.pws_weather_3n
      - sensor.pws_weather_4d
      - sensor.pws_weather_4n
      - sensor.pws_wind_1d_mph
      - sensor.pws_wind_mph
      - sensor.sunrise_time
      - sensor.sunset_time
      - sensor.exchange_rate_1_btc
      - sensor.ethereum

logbook:
  exclude:
    entities:
      - sensor.pws_alerts
      - sensor.pws_precip_1d
      - sensor.pws_precip_1d_in
      - sensor.pws_temp_f
      - sensor.pws_temp_high_1d_f
      - sensor.pws_temp_high_record_f
      - sensor.pws_temp_low_1d_f
      - sensor.pws_temp_low_record_f
      - sensor.pws_weather_1d
      - sensor.pws_weather_1n
      - sensor.pws_weather_2d
      - sensor.pws_weather_2n
      - sensor.pws_weather_3d
      - sensor.pws_weather_3n
      - sensor.pws_weather_4d
      - sensor.pws_weather_4n
      - sensor.pws_wind_1d_mph
      - sensor.pws_wind_mph
      - sensor.sunrise_time
      - sensor.sunset_time
      - sensor.exchange_rate_1_btc
      - sensor.ethereum
      - binary_sensor.master_bath_sensor_121
      - binary_sensor.motion_sensor_128
tts:
  platform: google

sun:

# Enable MQTT
mqtt:
  broker: !secret mqtt_ip
  port: 8883
  username: !secret mqtt_user
  password: !secret mqtt_password
#  certificate: /etc/mosquitto/certs/ca.crt
  certificate: /etc/ssl/certs/ca-certificates.crt
#  tls_insecure: true
#  protocol: 3.1

# Device Tracker
device_tracker:
  - platform: tplink
    host: !secret router_ip
    username: !secret router_username
    password: !secret router_password
    track_new_devices: false
#  - platform: owntracks
#    max_gps_accuracy: 200

##########################################
# Lights
##########################################

# Desk LEDs
light:
  - platform: flux_led
    devices:
      192.168.1.103:
        name: mancave_desk
        mode: rgb

##########################################
# Vera
##########################################

vera:
  vera_controller_url: !secret vera_ip
  exclude: [ 166, 152, 144]
#  lights: [ 118, 123, 115, 135, 133, 103, 104, 170, 160, 107, 120]

##########################################
# Media Players
##########################################
 
media_player:

# Living Room Kodi
  - platform: kodi
    host: !secret kodi1_ip
    port: 8080
    name: Living Room Kodi
    username: !secret kodi1_user
    password: !secret kodi1_pass

# Bedroom Kodi
  - platform: kodi
    host: !secret kodi2_ip
    port: 8080
    name: Bedroom Kodi

# Denon Receiver
  - platform: denonavr
    host: !secret denonavr_ip

##########################################
# Cams
##########################################

camera:

# Back Door Cam
  - platform: mjpeg
    mjpeg_url: !secret bdcam_url
    name: Back Door
    username: !secret bdcam_user
    password: !secret bdcam_pass

# Front Door Cam
  - platform: mjpeg
    mjpeg_url: !secret fdcam_url
    name: Front Door
    username: !secret fdcam_user
    password: !secret fdcam_pass

# Man Cave Cam
  - platform: mjpeg
    mjpeg_url: !secret mccam_url
    name: Man Cave Camera
    username: !secret mccam_user
    password: !secret mccam_pass

#### Not actual cams, but images to use in HA

# Solar alerts

  - platform: generic
    still_image_url: http://www.n3kl.org/sun/images/status.gif
    name: Solar X-Rays

  - platform: generic
    still_image_url: http://www.n3kl.org/sun/images/kpstatus.gif
    name: Geomagnetic Field
    

##########################################
# Sensors
##########################################

sensor:

# Weather Underground
  - platform: wunderground
    api_key: !secret wu_api
    monitored_conditions:
      - weather_1d
      - weather_1n
      - weather_2d
      - weather_2n
      - weather_3d
      - weather_3n
      - weather_4d
      - weather_4n
      - temp_high_record_f
      - temp_high_1d_f
      - temp_f
      - temp_low_1d_f
      - temp_low_record_f
      - precip_1d
      - precip_1d_in
      - wind_mph
      - wind_1d_mph
      - alerts

# Dark Sky
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - temperature
      - humidity
      - wind_speed
      - pressure
      - wind_bearing
      - apparent_temperature
      - icon
      - precip_probability
      - precip_intensity
      - cloud_cover

# Next Sunrise/Sunset Times
  - platform: template
    sensors:
      sunset_time:
        value_template: '{% set timestamp = as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%I:%M %p") %} {{ timestamp.lstrip("0") }}'
        friendly_name: "Sunset"

  - platform: template
    sensors:
      sunrise_time:
        value_template: '{% set timestamp = as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%I:%M %p") %} {{ timestamp.lstrip("0") }}'
        friendly_name: "Sunrise"

# Pi-Hole
  - platform: pi_hole
    host: !secret pi_hole_ip
    monitored_conditions:
      - dns_queries_today
      - ads_blocked_today
      - ads_percentage_today

# Gets public IP
  - platform: dnsip
    scan_interval: 1800

# Harmony Status
  - platform: template
    sensors:
      harmony_living_room:
        value_template: '{{states.remote.living_room.attributes.current_activity }}'
        friendly_name: 'Living Room'

# SABnzbd
  - platform: sabnzbd
    host: !secret sabnzbd_ip
    port: !secret sabnzbd_port
    api_key: !secret sabnzbd_api
    monitored_variables:
      - 'current_status'
      - 'speed'
      - 'queue_size'
      - 'queue_remaining'
      - 'disk_size'
      - 'disk_free'

# CoinMarketCap
  - platform: coinmarketcap
    currency: ethereum
# Bitcoin
  - platform: bitcoin
    display_options:
      - exchangerate

# USPS
  - platform: usps
    username: !secret usps_username
    password: !secret usps_password


# Vera Home mode
  - platform: rest
    name: "House Mode"
    resource: !secret hmode_url

  - platform: template
    sensors:
      homemode:
        friendly_name: 'House Mode'
        value_template:  >-
            {%- if is_state("sensor.house_mode", "1") %}
              Home
            {% elif is_state("sensor.house_mode", "2") %}
              Away
            {% elif is_state("sensor.house_mode", "3") %}
              Night
            {% elif is_state("sensor.house_mode", "4") %}
              Vacation
            {%- endif %}

binary_sensor:

# Detect ISS position
#  - platform: iss
#    name: ISS

##########################################
# Remote
##########################################

remote:

# Harmony Remote
  - platform: harmony
    name: Living Room
    host: !secret livingroom_harmony_ip

##########################################
# Telegram Bot
##########################################

telegram_bot:
  platform: polling
  api_key:  !secret telegram_bot_api_key
  allowed_chat_ids:
    - !secret e_chat_id
    - !secret v_chat_id

notify:
  - name: telegram_e
    platform: telegram
    chat_id: !secret e_chat_id
  - name: telegram_v
    platform: telegram
    chat_id: !secret v_chat_id
    
#########################################
# Zones
#########################################
zone:
  name: !secret e_work_name
  latitude: !secret e_work_lat
  longitude: !secret e_work_long
  radius: 200
  icon: mdi:company

zone 2:
  name: !secret v_work_name
  latitude: !secret v_work_lat
  longitude: !secret v_work_long
  radius: 200
  icon: mdi:cart

#########################################
# iframes
#########################################
panel_iframe:
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html

  dakboard:
    title: Events
    url: !secret dakboard_url
    icon: mdi:calendar

#########################################
# Shell Commands
#########################################

shell_command:
  br_lightsoff: !secret brlightsoff_url
  vera_mode_home: !secret homemode_url
  vera_mode_night: !secret nightmode_url
#  camera_default: !secret camdef_url
#  camera_privacy: !secret campri_url
  bdcam_def: !secret bdcam_def_url
  fdcam_def: !secret fdcam_def_url
  bdcam_priv: !secret bdcam_priv_url
  fdcam_priv: !secret fdcam_priv_url

#########################################
# Emulated Hue Bridge
#########################################

emulated_hue:
  type: alexa
  expose_by_default: false

#########################################
# Google Calendar
#########################################

#google:
#  client_id: !secret gcal_client
#  client_secret: !secret gcal_secret
#  track_new_calendar: False

#########################################
# Harmony Control
#########################################

input_select:
  living_room_tv:
    name: Living Room TV
    options:
      - Select Activity
      - Watch TV
      - Watch Kodi
      - Listen to Music
      - Chromecast
      - WiiU
      - Power Off
    initial: Select Activity
    icon: mdi:monitor

script:

# Vera Scenes

  br_lightsoff:
    sequence:
      service: shell_command.br_lightsoff
  vera_mode_home:
    sequence:
      service: shell_command.vera_mode_home
  vera_mode_night:
    sequence:
      service: shell_command.vera_mode_night

  camera_default:
    sequence:
      - service: shell_command.bdcam_def
      - service: shell_command.fdcam_def

  camera_privacy:
    sequence:
      - service: shell_command.bdcam_priv
      - service: shell_command.fdcam_priv

# Back to Harmony Stuff

  watch_kodi:
    sequence:
    - service: remote.turn_on
      entity_id: remote.living_room
      data:
        activity: "25502126"

  tv:
    sequence:
    - service: remote.turn_on
      entity_id: remote.living_room
      data:
        activity: "25502319"

  chromecast:
    sequence:
    - service: remote.turn_on
      entity_id: remote.living_room
      data:
        activity: "25502458"

  wiiu:
    sequence:
    - service: remote.turn_on
      entity_id: remote.living_room
      data:
        activity: "25502478"

  music:
    sequence:
    - service: remote.turn_on
      entity_id: remote.living_room
      data:
        activity: "25502405"

  tv_off:
    sequence:
    - service: remote.turn_off
      entity_id: remote.living_room

#########################################
# Includes
#########################################
group: !include groups.yaml
automation: !include automations.yaml

