homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customize
  auth_providers:
    - type: homeassistant

frontend:
  themes: !include_dir_merge_named themes/
  javascript_version: latest

lovelace:
  mode: yaml

config:

mobile_app:

logger:
  default: error
  logs:
    DenonAVR: fatal
#    homeassistant.components.device_tracker: debug

system_health:

http:
#  api_password: !secret http_pass
  base_url: !secret base_url
  server_port: 8254
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1



# Updater Stuff
updater:

# HACS
hacs:
  token: !secret hacs_token
  theme: true
  python_script: true

discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

recorder:
  #db_url: !secret mysql_url
  purge_keep_days: 5
  exclude:
    domains:
      - camera
      - zone
      - weather
    entities:
      - sensor.sunrise_time
      - sensor.sunset_time
      - sensor.myipopendnscom
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_humidity
      - sensor.dark_sky_icon
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_pressure
      - sensor.dark_sky_temperature
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_speed
      - sensor.date
      - sensor.simple_date
      - sensor.simple_time
      - sensor.solar_angle
      - sensor.ssl_certificate_expiry
      - sensor.flyers
      - sensor.hacs
      - sensor.home_team
      - sensor.away_team
      - sensor.wral
      - sensor.current_version
      - sensor.untappd_badge
      - sensor.untappd_beer
      - sensor.untappd_followings
      - sensor.untappd_last_badge_robotsfearme
      - sensor.untappd_last_check_in_robotsfearme
      - sensor.untappd_wishlist_robotsfearme

history:
  exclude:
    domains:
      - automation
      - updater
      - sun
      - script
      - group
      - camera
      - zone
      - weather
    entities:
      - sensor.sunrise_time
      - sensor.sunset_time
      - sensor.myipopendnscom
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_humidity
      - sensor.dark_sky_icon
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_pressure
      - sensor.dark_sky_temperature
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_speed
      - sensor.date
      - sensor.simple_date
      - sensor.simple_time
      - sensor.solar_angle
      - sensor.ssl_certificate_expiry
      - sensor.flyers
      - sensor.hacs
      - sensor.home_team
      - sensor.away_team
      - sensor.wral
      - sensor.current_version
      - sensor.untappd_badge
      - sensor.untappd_beer
      - sensor.untappd_followings
      - sensor.untappd_last_badge_robotsfearme
      - sensor.untappd_last_check_in_robotsfearme
      - sensor.untappd_wishlist_robotsfearme

logbook:
  exclude:
    domains:
      - zone
      - updater
      - weather
    entities:
      - sensor.sunrise_time
      - sensor.sunset_time
      - sensor.myipopendnscom
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_humidity
      - sensor.dark_sky_icon
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_pressure
      - sensor.dark_sky_temperature
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_speed
      - sensor.date
      - sensor.simple_date
      - sensor.simple_time
      - sensor.solar_angle
      - sensor.ssl_certificate_expiry
      - sensor.flyers
      - sensor.hacs
      - sensor.home_team
      - sensor.away_team
      - sensor.wral
      - sensor.current_version
      - sensor.untappd_badge
      - sensor.untappd_beer
      - sensor.untappd_followings
      - sensor.untappd_last_badge_robotsfearme
      - sensor.untappd_last_check_in_robotsfearme
      - sensor.untappd_wishlist_robotsfearme

sun:

# Enable MQTT - not needed right now
#mqtt:
#  broker: !secret mqtt_ip
#  port: 8883
#  username: !secret mqtt_user
#  password: !secret mqtt_password
#  certificate: /etc/mosquitto/certs/ca.crt
#  certificate: /etc/ssl/certs/ca-certificates.crt
#  tls_insecure: true
#  protocol: 3.1

##########################################
# Device Tracker & Presence
##########################################

unifi:
  controllers:
    - host: !secret unifi_ip
      site: Default
      dont_track_wired_clients: true

person:
  - name: Eric
    id: eric
    device_trackers:
      - device_tracker.galaxy_s7
  - name: Val
    id: val
    device_trackers:
      - device_tracker.galaxy_j7

##########################################
# Lights
##########################################

# Desk LEDs
light:
  - platform: flux_led
    devices:
      192.168.1.122:
        name: mancave_desk
        mode: rgb
      192.168.1.149:
        name: pin_board
        mode: rgbw
      192.168.1.169:
        name: tv
        mode: rgbw
        custom_effect:
          speed_pct: 7
          transition: gradual
          colors:
            - [178,34,34]
            - [255,0,0]
            - [255,69,0]
            - [255,165,0]
            - [255,255,0]
            - [54,205,50]
            - [07,142,35]
            - [0,128,0]
            - [0,255,0]
            - [0,250,154]
            - [0,128,128]
            - [0,255,255]
            - [0,0,255]
            - [138,43,226]
            - [139,0,139]
            - [255,0,255]

  - platform: limitlessled
    bridges:
      - host: 192.168.1.148
        groups:
        - number: 1
          name: Mancave
          type: rgbww
        - number: 1
          name: Wifi Box
          type: bridge-led

##########################################
# Vera
##########################################

vera:
  vera_controller_url: !secret vera_ip
  exclude: [ 166, 152, 144]
#  lights: [ 118, 123, 115, 135, 133, 103, 104, 170, 160, 107, 120]

##########################################
# Media Players
##########################################

media_player:

# Living Room Kodi
  - platform: kodi
    host: !secret kodi1_ip
    port: 8080
    name: Living Room Kodi
    username: !secret kodi1_user
    password: !secret kodi1_pass

# Bedroom Kodi
  - platform: kodi
    host: !secret kodi2_ip
    port: 8080
    name: Bedroom Kodi

# Denon Receiver
  - platform: denonavr
    host: !secret denonavr_ip

##########################################
# Cams
##########################################

camera:

# Back Door Cam
  - platform: mjpeg
    mjpeg_url: !secret bdcam_url
    name: Back Door
    username: !secret bdcam_user
    password: !secret bdcam_pass

# Front Door Cam
  - platform: mjpeg
    mjpeg_url: !secret fdcam_url
    name: Front Door
    username: !secret fdcam_user
    password: !secret fdcam_pass

# Man Cave Cam
  - platform: mjpeg
    mjpeg_url: !secret mccam_url
    name: Man Cave Camera
    username: !secret mccam_user
    password: !secret mccam_pass

#### Not actual cams, but images to use in HA

# Solar alerts

  - platform: generic
    still_image_url: http://www.n3kl.org/sun/images/status.gif
    name: Solar X-Rays

  - platform: generic
    still_image_url: http://www.n3kl.org/sun/images/kpstatus.gif
    name: Geomagnetic Field

# NWS Radar
  - platform: nwsradar
    station: RAX
    style: Enhanced
    frames: 10

##########################################
# Sensors
##########################################

sensor:

# LR Temp
  - platform: template
    sensors:
      current_temperature:
        friendly_name: Living Room Temp
        value_template: "{{ state_attr('climate.thermostat_147', 'current_temperature') }}"
        unit_of_measurement: '°'

# Newest Version of HASS Available
  - platform: template
    sensors:
      hass_avail_version:
        friendly_name: HASS Version Available
        value_template: "{{ state_attr('binary_sensor.updater', 'newest_version') }}"

# Weather Underground
#  - platform: wunderground
#    api_key: !secret wu_api
#    pwd_id: KNCFUQUA65
#    monitored_conditions:
#      - weather_1d
#      - weather_1n
#      - weather_2d
#      - weather_2n
#      - weather_3d
#      - weather_3n
#      - weather_4d
#      - weather_4n
#      - temp_high_record_f
#      - temp_high_1d_f
#      - temp_f
#      - temp_low_1d_f
#      - temp_low_record_f
#      - precip_1d
#      - precip_1d_in
#      - wind_mph
#      - wind_1d_mph
#      - alerts

# Dark Sky
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - temperature
      - humidity
      - wind_speed
      - pressure
      - wind_bearing
      - apparent_temperature
      - icon
      - precip_probability
      - precip_intensity
      - cloud_cover

# Next Sunrise/Sunset Times
  - platform: template
    sensors:
      sunset_time:
        value_template: '{% set timestamp = as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%I:%M %p") %} {{ timestamp.lstrip("0") }}'
        friendly_name: "Sunset"

  - platform: template
    sensors:
      sunrise_time:
        value_template: '{% set timestamp = as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%I:%M %p") %} {{ timestamp.lstrip("0") }}'
        friendly_name: "Sunrise"

  - platform: template
    sensors:
      solar_angle:
        friendly_name: "Sun angle"
        unit_of_measurement: 'degrees'
        value_template: "{{ states.sun.sun.attributes.elevation }}"

# Pi-Hole
#  - platform: pi_hole
#    host: !secret pi_hole_ip
#    monitored_conditions:
#      - dns_queries_today
#      - ads_blocked_today
#      - ads_percentage_today

# RSS Feed
  - platform: feedparser
    feed_url: 'http://www.wral.com/news/rss/48/'
    name: WRAL
    show_topn: 10
    inclusions:
      - title
      - description
      - category
      #- media:thumbnail
      - pubDate

# NHL
  - platform: nhl_api
    team_id: 4
    name: Flyers
    scan_interval: 60

  - platform: template
    sensors:
      away_team:
        friendly_name_template: '{{ states.sensor.flyers.attributes.away_name }}'
        value_template: '{{ states.sensor.flyers.attributes.away_score }}'
        entity_picture_template: '{{ states.sensor.flyers.attributes.away_logo }}'
      home_team:
        friendly_name_template: '{{ states.sensor.flyers.attributes.home_name }}'
        value_template: '{{ states.sensor.flyers.attributes.home_score }}'
        entity_picture_template: '{{ states.sensor.flyers.attributes.home_logo }}'

# Gets public IP
  - platform: dnsip
    scan_interval: 1800

  - platform: cert_expiry
    host: evilrobot.space


# Harmony Status
  - platform: template
    sensors:
      harmony_living_room:
        value_template: '{{states.remote.living_room.attributes.current_activity }}'
        friendly_name: 'Living Room'

#  - platform: template
#    sensors:
#      lr_avr_vol:
#        value_template: "{{ states.media_player.denon_avr_s720w.attributes.volume_level | float * 100 }}"

# Sonarr Upcoming Media
  - platform: sonarr_upcoming_media
    urlbase: sonarr
    api_key: !secret sonarr_api

# SABnzbd
#  - platform: sabnzbd
#    host: !secret sabnzbd_ip
#    port: !secret sabnzbd_port
#    api_key: !secret sabnzbd_api
#    monitored_variables:
#      - 'current_status'
#      - 'speed'
#      - 'queue_size'
#      - 'queue_remaining'
#      - 'disk_size'
#      - 'disk_free'

# Vera Home mode
  - platform: rest
    name: "House Mode"
    resource: !secret hmode_url

  - platform: template
    sensors:
      homemode:
        friendly_name: 'House Mode'
        value_template:  >-
            {%- if is_state("sensor.house_mode", "1") %}
              Home
            {% elif is_state("sensor.house_mode", "2") %}
              Away
            {% elif is_state("sensor.house_mode", "3") %}
              Night
            {% elif is_state("sensor.house_mode", "4") %}
              Vacation
            {%- endif %}

# Versions sensor
  - platform: version

# Date and Time
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'time_date'
  - platform: template
    sensors:
      simple_time:
        entity_id: sensor.time
        friendly_name: "Time"
        value_template: "{{ now().strftime('%I:%M %P') }}"
  - platform: template
    sensors:
      simple_date:
        entity_id: sensor.time
        friendly_name: "Date"
        value_template: "{{ now().strftime('%A %b %d, %Y') }}"

# Untappd sensor and templating
  - platform: untappd
    username: !secret untappd_user
    id: !secret untappd_id
    secret: !secret untappd_secret

  - platform: template
    sensors:
      untappd_badge:
#        value_template: "Last Badge: {{ states.sensor.untappd_last_badge_robotsfearme.attributes.badge }} (Level {{ states.sensor.untappd_last_badge_robotsfearme.attributes.level }})"
        value_template: "Last Badge: {{ states.sensor.untappd_last_badge_robotsfearme.attributes.badge }}"
  - platform: template
    sensors:
      untappd_beer:
        value_template: "Last Beer: {{ states.sensor.untappd_last_check_in_robotsfearme.attributes.beer }} ({{ states.sensor.untappd_last_check_in_robotsfearme.attributes.abv }})"

  - platform: template
    sensors:
      untappd_followings:
#        unit_of_measurement: followers
        value_template: "{{ states.sensor.untappd_last_check_in_robotsfearme.attributes.followings }}"

  - platform: template
    sensors:
      untappd_checked:
#        unit_of_measurement: checkins
        value_template: "{{ states.sensor.untappd_last_check_in_robotsfearme.attributes.checkins }}"

  - platform: template
    sensors:
      untappd_total_beers:
#        unit_of_measurement: beers
        value_template: "{{ states.sensor.untappd_last_check_in_robotsfearme.attributes.total_beers }}"

  - platform: template
    sensors:
      untappd_total_badges:
#        unit_of_measurement: badges
        value_template: "{{ states.sensor.untappd_last_check_in_robotsfearme.attributes.total_badges }}"

#  - platform: duke_energy
#    username: !secret duke_user
#    password: !secret duke_pass

  - platform: template
    sensors:
      power_avg_use:
        friendly_name: Average Usage
        value_template: "{{ state_attr('sensor.duke_energy_43413318', 'last_bills_average_usage') }}"
        unit_of_measurement: 'kW-h'
  - platform: template
    sensors:
      power_lastbill_use:
        friendly_name: Last Bill Usage
        value_template: "{{ state_attr('sensor.duke_energy_43413318', 'last_bills_usage') }}"
        unit_of_measurement: 'kW-h'

binary_sensor:

##########################################
# Weather (New method)
##########################################
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily
    name: Weather
##########################################
# Remote
##########################################

remote:

# Harmony Remote
  - platform: harmony
    name: Living Room
    host: !secret livingroom_harmony_ip

##########################################
# Telegram Bot
##########################################

telegram_bot:
  platform: polling
  api_key:  !secret telegram_bot_api_key
  allowed_chat_ids:
    - !secret e_chat_id
    - !secret v_chat_id

#########################################
# Notifications
#########################################

notify:
  - name: telegram_e
    platform: telegram
    chat_id: !secret e_chat_id
  - name: telegram_v
    platform: telegram
    chat_id: !secret v_chat_id
#  - name: notify_chrome
#    platform: html5
#    gcm_api_key: !secret gcm_sender_key
#    gcm_sender_id: !secret gcm_sender_id

#########################################
# Zones
#########################################

zone:
  name: !secret e_work_name
  latitude: !secret e_work_lat
  longitude: !secret e_work_long
  radius: 200
  icon: mdi:company

zone 2:
  name: !secret v_work_name
  latitude: !secret v_work_lat
  longitude: !secret v_work_long
  radius: 200
  icon: mdi:cart

#########################################
# Emulated Hue Bridge
#########################################

emulated_hue:
  type: alexa
  expose_by_default: false

#########################################
# Google calendar
#########################################
google:
  client_id: !secret gcal_client
  client_secret: !secret gcal_secret

#########################################
# Harmony Switches
#########################################
switch:
  - platform: template
    switches:
      lr_tv:
        friendly_name: TV
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Watch TV') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'Watch TV'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'
      lr_kodi:
        friendly_name: Kodi
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Watch Kodi') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'Watch Kodi'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'
      lr_wiiu:
        friendly_name: Switch
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'WiiU' ) }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'WiiU'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'
      lr_music:
        friendly_name: Music
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Listen to Music' ) }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'Listen to Music'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'
      lr_chromecast:
        friendly_name: Chromecast
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Chromecast' ) }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'Chromecast'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'
      lr_steam:
        friendly_name: Steam
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Play Steam' ) }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'Play Steam'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'

#########################################
# Includes
#########################################
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
