homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes/
  javascript_version: latest

lovelace:
  mode: yaml

config:

logger:
  default: error
  logs:
    DenonAVR: fatal
#    homeassistant.components.device_tracker: debug

system_health:

http:
  api_password: !secret http_pass
  base_url: !secret base_url
  server_port: 8254
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.0/24

# Updater Stuff
updater:

# HACS
hacs:
  token: !secret hacs_token

discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

recorder:
  db_url: !secret mysql_url
  purge_keep_days: 5
  exclude:
    domains:
      - camera
      - zone
    entities:
      - sensor.pws_alerts
      - sensor.pws_precip_1d
      - sensor.pws_precip_1d_in
      - sensor.pws_temp_high_1d_f
      - sensor.pws_temp_high_record_f
      - sensor.pws_temp_low_1d_f
      - sensor.pws_temp_low_record_f
      - sensor.pws_weather_1d
      - sensor.pws_weather_1n
      - sensor.pws_weather_2d
      - sensor.pws_weather_2n
      - sensor.pws_weather_3d
      - sensor.pws_weather_3n
      - sensor.pws_weather_4d
      - sensor.pws_weather_4n
      - sensor.pws_wind_1d_mph
      - sensor.sunrise_time
      - sensor.sunset_time
      - sensor.myipopendnscom
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_humidity
      - sensor.dark_sky_icon
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_pressure
      - sensor.dark_sky_temperature
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_speed
      - sensor.untappd_badge
      - sensor.untappd_beer
      - sensor.untappd_followings
      - sensor.untappd_last_badge_robotsfearme
      - sensor.untappd_last_check_in_robotsfearme
      - sensor.untappd_wishlist_robotsfearme

history:
  exclude:
    domains:
      - automation
      - updater
      - sun
      - script
      - group
      - camera
      - zone
    entities:
      - sensor.pws_alerts
      - sensor.pws_precip_1d
      - sensor.pws_precip_1d_in
      - sensor.pws_temp_high_1d_f
      - sensor.pws_temp_high_record_f
      - sensor.pws_temp_low_1d_f
      - sensor.pws_temp_low_record_f
      - sensor.pws_weather_1d
      - sensor.pws_weather_1n
      - sensor.pws_weather_2d
      - sensor.pws_weather_2n
      - sensor.pws_weather_3d
      - sensor.pws_weather_3n
      - sensor.pws_weather_4d
      - sensor.pws_weather_4n
      - sensor.pws_wind_1d_mph
      - sensor.sunrise_time
      - sensor.sunset_time
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_humidity
      - sensor.dark_sky_icon
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_pressure
      - sensor.dark_sky_temperature
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_speed
      - sensor.untappd_badge
      - sensor.untappd_beer
      - sensor.untappd_followings
      - sensor.untappd_last_badge_robotsfearme
      - sensor.untappd_last_check_in_robotsfearme
      - sensor.untappd_wishlist_robotsfearme

logbook:
  exclude:
    domains:
      - zone
      - updater
    entities:
      - sensor.pws_alerts
      - sensor.pws_precip_1d
      - sensor.pws_precip_1d_in
      - sensor.pws_temp_high_1d_f
      - sensor.pws_temp_high_record_f
      - sensor.pws_temp_low_1d_f
      - sensor.pws_temp_low_record_f
      - sensor.pws_weather_1d
      - sensor.pws_weather_1n
      - sensor.pws_weather_2d
      - sensor.pws_weather_2n
      - sensor.pws_weather_3d
      - sensor.pws_weather_3n
      - sensor.pws_weather_4d
      - sensor.pws_weather_4n
      - sensor.pws_wind_1d_mph
      - sensor.sunrise_time
      - sensor.sunset_time
      - binary_sensor.master_bath_sensor_121
      - binary_sensor.motion_sensor_128
      - sensor.dark_sky_icon
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_humidity
      - sensor.dark_sky_icon
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_pressure
      - sensor.dark_sky_temperature
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_speed
      - sensor.untappd_badge
      - sensor.untappd_beer
      - sensor.untappd_followings
      - sensor.untappd_last_badge_robotsfearme
      - sensor.untappd_last_check_in_robotsfearme
      - sensor.untappd_wishlist_robotsfearme

sun:

# Enable MQTT - not needed right now
#mqtt:
#  broker: !secret mqtt_ip
#  port: 8883
#  username: !secret mqtt_user
#  password: !secret mqtt_password
#  certificate: /etc/mosquitto/certs/ca.crt
#  certificate: /etc/ssl/certs/ca-certificates.crt
#  tls_insecure: true
#  protocol: 3.1

# Device Tracker
device_tracker:
  - platform: unifi
    username: !secret ap_username
    password: !secret ap_password
    verify_ssl: false
    track_new_devices: false

##########################################
# Lights
##########################################

# Desk LEDs
light:
  - platform: flux_led
    devices:
      192.168.1.122:
        name: mancave_desk
        mode: rgb
      192.168.1.149:
        name: pin_board
        mode: rgbw

  - platform: limitlessled
    bridges:
      - host: 192.168.1.148
        groups:
        - number: 1
          name: Mancave
          type: rgbww
        - number: 1
          name: Wifi Box
          type: bridge-led


##########################################
# Vera
##########################################

vera:
  vera_controller_url: !secret vera_ip
  exclude: [ 166, 152, 144]
#  lights: [ 118, 123, 115, 135, 133, 103, 104, 170, 160, 107, 120]

##########################################
# Media Players
##########################################

media_player:

# Living Room Kodi
  - platform: kodi
    host: !secret kodi1_ip
    port: 8080
    name: Living Room Kodi
    username: !secret kodi1_user
    password: !secret kodi1_pass

# Bedroom Kodi
  - platform: kodi
    host: !secret kodi2_ip
    port: 8080
    name: Bedroom Kodi

# Denon Receiver
  - platform: denonavr
    host: !secret denonavr_ip

##########################################
# Cams
##########################################

camera:

# Back Door Cam
  - platform: mjpeg
    mjpeg_url: !secret bdcam_url
    name: Back Door
    username: !secret bdcam_user
    password: !secret bdcam_pass

# Front Door Cam
  - platform: mjpeg
    mjpeg_url: !secret fdcam_url
    name: Front Door
    username: !secret fdcam_user
    password: !secret fdcam_pass

# Man Cave Cam
  - platform: mjpeg
    mjpeg_url: !secret mccam_url
    name: Man Cave Camera
    username: !secret mccam_user
    password: !secret mccam_pass

#### Not actual cams, but images to use in HA

# Solar alerts

  - platform: generic
    still_image_url: http://www.n3kl.org/sun/images/status.gif
    name: Solar X-Rays

  - platform: generic
    still_image_url: http://www.n3kl.org/sun/images/kpstatus.gif
    name: Geomagnetic Field


##########################################
# Sensors
##########################################

sensor:

# LR Temp
  - platform: template
    sensors:
      current_temperature:
        friendly_name: Living Room Temp
        value_template: "{{ state_attr('climate.thermostat_147', 'current_temperature') }}"
        unit_of_measurement: '°'

# Weather Underground
#  - platform: wunderground
#    api_key: !secret wu_api
#    pwd_id: KNCFUQUA65
#    monitored_conditions:
#      - weather_1d
#      - weather_1n
#      - weather_2d
#      - weather_2n
#      - weather_3d
#      - weather_3n
#      - weather_4d
#      - weather_4n
#      - temp_high_record_f
#      - temp_high_1d_f
#      - temp_f
#      - temp_low_1d_f
#      - temp_low_record_f
#      - precip_1d
#      - precip_1d_in
#      - wind_mph
#      - wind_1d_mph
#      - alerts

# Dark Sky
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - temperature
      - humidity
      - wind_speed
      - pressure
      - wind_bearing
      - apparent_temperature
      - icon
      - precip_probability
      - precip_intensity
      - cloud_cover

# Next Sunrise/Sunset Times
  - platform: template
    sensors:
      sunset_time:
        value_template: '{% set timestamp = as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%I:%M %p") %} {{ timestamp.lstrip("0") }}'
        friendly_name: "Sunset"

  - platform: template
    sensors:
      sunrise_time:
        value_template: '{% set timestamp = as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%I:%M %p") %} {{ timestamp.lstrip("0") }}'
        friendly_name: "Sunrise"

  - platform: template
    sensors:
      solar_angle:
        friendly_name: "Sun angle"
        unit_of_measurement: 'degrees'
        value_template: "{{ states.sun.sun.attributes.elevation }}"

# Pi-Hole
#  - platform: pi_hole
#    host: !secret pi_hole_ip
#    monitored_conditions:
#      - dns_queries_today
#      - ads_blocked_today
#      - ads_percentage_today

# Gets public IP
  - platform: dnsip
    scan_interval: 1800

# Harmony Status
  - platform: template
    sensors:
      harmony_living_room:
        value_template: '{{states.remote.living_room.attributes.current_activity }}'
        friendly_name: 'Living Room'

# Denon AVR Volume
  - platform: template
    sensors:
      lr_avr_vol:
        value_template: "{{ states.media_player.denon_avr_s720w.attributes.volume_level | float * 100 }}"

# SABnzbd
#  - platform: sabnzbd
#    host: !secret sabnzbd_ip
#    port: !secret sabnzbd_port
#    api_key: !secret sabnzbd_api
#    monitored_variables:
#      - 'current_status'
#      - 'speed'
#      - 'queue_size'
#      - 'queue_remaining'
#      - 'disk_size'
#      - 'disk_free'

# Vera Home mode
  - platform: rest
    name: "House Mode"
    resource: !secret hmode_url

  - platform: template
    sensors:
      homemode:
        friendly_name: 'House Mode'
        value_template:  >-
            {%- if is_state("sensor.house_mode", "1") %}
              Home
            {% elif is_state("sensor.house_mode", "2") %}
              Away
            {% elif is_state("sensor.house_mode", "3") %}
              Night
            {% elif is_state("sensor.house_mode", "4") %}
              Vacation
            {%- endif %}

# Versions sensor
  - platform: version

# Untappd sensor and templating
  - platform: untappd
    username: !secret untappd_user
    id: !secret untappd_id
    secret: !secret untappd_secret

  - platform: template
    sensors:
      untappd_badge:
#        value_template: "Last Badge: {{ states.sensor.untappd_last_badge_robotsfearme.attributes.badge }} (Level {{ states.sensor.untappd_last_badge_robotsfearme.attributes.level }})"
        value_template: "Last Badge: {{ states.sensor.untappd_last_badge_robotsfearme.attributes.badge }}"
  - platform: template
    sensors:
      untappd_beer:
        value_template: "Last Beer: {{ states.sensor.untappd_last_check_in_robotsfearme.attributes.beer }} ({{ states.sensor.untappd_last_check_in_robotsfearme.attributes.abv }})"

  - platform: template
    sensors:
      untappd_followings:
#        unit_of_measurement: followers
        value_template: "{{ states.sensor.untappd_last_check_in_robotsfearme.attributes.followings }}"

  - platform: template
    sensors:
      untappd_checked:
#        unit_of_measurement: checkins
        value_template: "{{ states.sensor.untappd_last_check_in_robotsfearme.attributes.checkins }}"

  - platform: template
    sensors:
      untappd_total_beers:
#        unit_of_measurement: beers
        value_template: "{{ states.sensor.untappd_last_check_in_robotsfearme.attributes.total_beers }}"

  - platform: template
    sensors:
      untappd_total_badges:
#        unit_of_measurement: badges
        value_template: "{{ states.sensor.untappd_last_check_in_robotsfearme.attributes.total_badges }}"

  - platform: duke_energy
    username: !secret duke_user
    password: !secret duke_pass

  - platform: template
    sensors:
      power_avg_use:
        friendly_name: Average Usage
        value_template: "{{ state_attr('sensor.duke_energy_43413318', 'last_bills_average_usage') }}"
        unit_of_measurement: 'kW-h'
  - platform: template
    sensors:
      power_lastbill_use:
        friendly_name: Last Bill Usage
        value_template: "{{ state_attr('sensor.duke_energy_43413318', 'last_bills_usage') }}"
        unit_of_measurement: 'kW-h'

binary_sensor:

##########################################
# Weather (New method)
##########################################
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily
    name: Weather
##########################################
# Remote
##########################################

remote:

# Harmony Remote
  - platform: harmony
    name: Living Room
    host: !secret livingroom_harmony_ip

##########################################
# Telegram Bot
##########################################

telegram_bot:
  platform: polling
  api_key:  !secret telegram_bot_api_key
  allowed_chat_ids:
    - !secret e_chat_id
    - !secret v_chat_id

#########################################
# Notifications
#########################################

notify:
  - name: telegram_e
    platform: telegram
    chat_id: !secret e_chat_id
  - name: telegram_v
    platform: telegram
    chat_id: !secret v_chat_id
#  - name: notify_chrome
#    platform: html5
#    gcm_api_key: !secret gcm_sender_key
#    gcm_sender_id: !secret gcm_sender_id

#########################################
# Zones
#########################################

zone:
  name: !secret e_work_name
  latitude: !secret e_work_lat
  longitude: !secret e_work_long
  radius: 200
  icon: mdi:company

zone 2:
  name: !secret v_work_name
  latitude: !secret v_work_lat
  longitude: !secret v_work_long
  radius: 200
  icon: mdi:cart

#########################################
# iframes
#########################################
panel_iframe:
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html

#########################################
# Shell Commands
#########################################

shell_command:
  party_play: 'curl -g "http://192.168.1.210:8080/jsonrpc?request={"jsonrpc":"2.0","id":"1","method":"Player.Open","params":{"item":{"file":"special://profile/playlists/music/Party.m3u"}}}"'

#########################################
# REST Commands
#########################################

rest_command:
  party_playlist:
    url: 'http://192.168.1.210:8080/jsonrpc?request={"jsonrpc":"2.0","id":"1","method":"Player.Open","params":{"item":{"file":"special://profile/playlists/music/Party.m3u"}}}'

#########################################
# Emulated Hue Bridge
#########################################

emulated_hue:
  type: alexa
  expose_by_default: false

#########################################
# USPS - Not working
#########################################

#usps:
#  username: !secret usps_username
#  password: !secret usps_password
#  driver: 'phantomjs'

#########################################
# Google calendar
#########################################
google:
  client_id: !secret gcal_client
  client_secret: !secret gcal_secret


#########################################
# Input Selects
#########################################

input_select:

# Harmony Control
  living_room_tv:
    name: Living Room TV
    options:
      - Select Activity
      - Watch TV
      - Watch Kodi
      - Listen to Music
      - Chromecast
      - WiiU
      - Steam Link
      - Power Off
    initial: Select Activity
    icon: mdi:monitor

# Chromecast Radio
  radio_station:
    name: 'Select Radio Station:'
    options:
      - JEMP
      - GD Radio
      - Nugs Radio
      - Hot 97
  chromecast_radio:
    name: 'Select Speakers:'
    options:
      - Living Room
      - Man Cave
      - Living and Bed
      - All
    initial: All
    icon: mdi:speaker-wireless


input_number:
  volume_radio:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05

#########################################
# Harmony Switches
#########################################
switch:
  - platform: template
    switches:
      lr_tv:
        friendly_name: TV
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Watch TV') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'Watch TV'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'
      lr_kodi:
        friendly_name: Kodi
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Watch Kodi') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'Watch Kodi'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'
      lr_wiiu:
        friendly_name: Switch
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'WiiU' ) }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'WiiU'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'
      lr_music:
        friendly_name: Music
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Listen to Music' ) }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'Listen to Music'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'
      lr_chromecast:
        friendly_name: Chromecast
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Chromecast' ) }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'Chromecast'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'
      lr_steam:
        friendly_name: Steam
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Play Steam' ) }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'Play Steam'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'

#########################################
# Includes
#########################################
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
