homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml

frontend:
  themes:
    solarized:
      primary-color: "#2aa198"
      disabled-text-color: "#859900"
      divider-color: "#586e75" #"rgba(255, 255, 255, 0.12)"
      paper-card-background-color: "#002b36"
      paper-grey-200: "#586e75"
      paper-item-icon-color: "#b58900"
      paper-listbox-background-color: "#002b36"
      paper-listbox-color: "#b58900"
      primary-background-color: "#073642"
      primary-text-color: "#839496"
      secondary-background-color: "#073642"
      secondary-text-color: "#859900"
      text-primary-color: "#839496"
      label-badge-background-color: "var(--secondary-background-color)"
      label-badge-text-color: "var(--text-primary-color)"
      paper-card-header-color: "#cb4b16"
      paper-grey-50: "#b58900"
      paper-item-icon-active-color: "#dc322f"
      paper-item-icon_-_color: "#FF00FF"   # no clue 
      paper-slider-active-color: "#dc322f"
      paper-slider-knob-color: "#dc322f"
      paper-slider-knob-start-color: "#b58900"
      paper-slider-pin-color: "#FF00FF"  # no clue
      paper-slider-secondary-color: "#dc322f"
      paper-toggle-button-checked-ink-color: "#dc322f"
      paper-toggle-button-checked-button-color: "#dc322f"
      paper-toggle-button-checked-bar-color: "#cb4b16"
      paper-toggle-button-unchecked-bar-color: "#b58900"
      table-row-background-color: "#002b36"
      table-row-alternative-background-color: "#073642"
      google-red: "#dc322f"
      google-green: "#859900"
      google-blue: "#268bd2"
      google-yellow: "#b58900"
      accent-color: "#cb4b16"
      paper-green: "#859900"
      paper-blue: "#268bd2"
      paper-orange: "#cb4b16"
  
    darkcyan:
    # Main colors that can be changed
      primary-color: "#00bcd4"
      disabled-text-color: "#545454"
      divider-color: "rgba(255, 255, 255, 0.12)"
      paper-card-background-color: "#4e4e4e"
      paper-grey-200: "#191919"
      paper-item-icon-color: "#d3d3d3"
      paper-listbox-background-color: "#202020"
      paper-listbox-color: "#FFFFFF"      
      primary-background-color: "#303030"
      primary-text-color: "#cfcfcf"      
      secondary-background-color: "#2b2b2b"
      secondary-text-color: "#04a7bc"
    # Colors based on variables, see above
      label-badge-background-color: "var(--secondary-background-color)"
      label-badge-text-color: "var(--text-primary-color)"
      paper-card-header-color: "#var(--paper-item-icon-color)"
      paper-grey-50: "var(--primary-text-color)"
      paper-item-icon-active-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--primary-text-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"     
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--primary-color)"
      paper-toggle-button-checked-bar-color: "var(--light-primary-color)"
      paper-toggle-button-unchecked-bar-color: "var(--primary-text-color)"

config:

logger:
  default: error
  logs:
    DenonAVR: fatal
#    homeassistant.components.device_tracker: debug

http:
  api_password: !secret http_pass
  base_url: !secret base_url
  server_port: 8254 
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true

updater:

discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

recorder:
  exclude:
    domains:
      - camera
    entities:
      - sensor.pws_alerts
      - sensor.pws_precip_1d
      - sensor.pws_precip_1d_in
      - sensor.pws_temp_f
      - sensor.pws_temp_high_1d_f
      - sensor.pws_temp_high_record_f
      - sensor.pws_temp_low_1d_f
      - sensor.pws_temp_low_record_f
      - sensor.pws_weather_1d
      - sensor.pws_weather_1n
      - sensor.pws_weather_2d
      - sensor.pws_weather_2n
      - sensor.pws_weather_3d
      - sensor.pws_weather_3n
      - sensor.pws_weather_4d
      - sensor.pws_weather_4n
      - sensor.pws_wind_1d_mph
      - sensor.pws_wind_mph
      - sensor.sunrise_time
      - sensor.sunset_time
      - sensor.exchange_rate_1_btc
      - sensor.ethereum
      - sensor.myipopendnscom

history:
  exclude:
    domains:
      - automation
      - updater
      - sun
      - script
      - group
      - camera
    entities:
      - sensor.pws_alerts
      - sensor.pws_precip_1d
      - sensor.pws_precip_1d_in
      - sensor.pws_temp_f
      - sensor.pws_temp_high_1d_f
      - sensor.pws_temp_high_record_f
      - sensor.pws_temp_low_1d_f
      - sensor.pws_temp_low_record_f
      - sensor.pws_weather_1d
      - sensor.pws_weather_1n
      - sensor.pws_weather_2d
      - sensor.pws_weather_2n
      - sensor.pws_weather_3d
      - sensor.pws_weather_3n
      - sensor.pws_weather_4d
      - sensor.pws_weather_4n
      - sensor.pws_wind_1d_mph
      - sensor.pws_wind_mph
      - sensor.sunrise_time
      - sensor.sunset_time
      - sensor.exchange_rate_1_btc
      - sensor.ethereum

logbook:
  exclude:
    entities:
      - sensor.pws_alerts
      - sensor.pws_precip_1d
      - sensor.pws_precip_1d_in
      - sensor.pws_temp_f
      - sensor.pws_temp_high_1d_f
      - sensor.pws_temp_high_record_f
      - sensor.pws_temp_low_1d_f
      - sensor.pws_temp_low_record_f
      - sensor.pws_weather_1d
      - sensor.pws_weather_1n
      - sensor.pws_weather_2d
      - sensor.pws_weather_2n
      - sensor.pws_weather_3d
      - sensor.pws_weather_3n
      - sensor.pws_weather_4d
      - sensor.pws_weather_4n
      - sensor.pws_wind_1d_mph
      - sensor.pws_wind_mph
      - sensor.sunrise_time
      - sensor.sunset_time
      - binary_sensor.master_bath_sensor_121
      - binary_sensor.motion_sensor_128
      - sensor.dark_sky_icon
tts:
  platform: google

sun:

# Enable MQTT - not needed right now
#mqtt:
#  broker: !secret mqtt_ip
#  port: 8883
#  username: !secret mqtt_user
#  password: !secret mqtt_password
#  certificate: /etc/mosquitto/certs/ca.crt
#  certificate: /etc/ssl/certs/ca-certificates.crt
#  tls_insecure: true
#  protocol: 3.1

# Device Tracker
device_tracker:
  - platform: unifi
    username: !secret ap_username
    password: !secret ap_password
    verify_ssl: false
    track_new_devices: false

##########################################
# Lights
##########################################

# Desk LEDs
light:
  - platform: flux_led
    devices:
      192.168.1.122:
        name: mancave_desk
        mode: rgb

##########################################
# Vera
##########################################

vera:
  vera_controller_url: !secret vera_ip
  exclude: [ 166, 152, 144]
#  lights: [ 118, 123, 115, 135, 133, 103, 104, 170, 160, 107, 120]

##########################################
# Media Players
##########################################
 
media_player:

# Living Room Kodi
  - platform: kodi
    host: !secret kodi1_ip
    port: 8080
    name: Living Room Kodi
    username: !secret kodi1_user
    password: !secret kodi1_pass

# Bedroom Kodi
  - platform: kodi
    host: !secret kodi2_ip
    port: 8080
    name: Bedroom Kodi

# Denon Receiver
  - platform: denonavr
    host: !secret denonavr_ip

##########################################
# Cams
##########################################

camera:

# Back Door Cam
  - platform: mjpeg
    mjpeg_url: !secret bdcam_url
    name: Back Door
    username: !secret bdcam_user
    password: !secret bdcam_pass

# Front Door Cam
  - platform: mjpeg
    mjpeg_url: !secret fdcam_url
    name: Front Door
    username: !secret fdcam_user
    password: !secret fdcam_pass

# Man Cave Cam
  - platform: mjpeg
    mjpeg_url: !secret mccam_url
    name: Man Cave Camera
    username: !secret mccam_user
    password: !secret mccam_pass

#### Not actual cams, but images to use in HA

# Solar alerts

  - platform: generic
    still_image_url: http://www.n3kl.org/sun/images/status.gif
    name: Solar X-Rays

  - platform: generic
    still_image_url: http://www.n3kl.org/sun/images/kpstatus.gif
    name: Geomagnetic Field
    

##########################################
# Sensors
##########################################

sensor:

# Weather Underground
  - platform: wunderground
    api_key: !secret wu_api
    monitored_conditions:
      - weather_1d
      - weather_1n
      - weather_2d
      - weather_2n
      - weather_3d
      - weather_3n
      - weather_4d
      - weather_4n
      - temp_high_record_f
      - temp_high_1d_f
      - temp_f
      - temp_low_1d_f
      - temp_low_record_f
      - precip_1d
      - precip_1d_in
      - wind_mph
      - wind_1d_mph
      - alerts

# Dark Sky
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - temperature
      - humidity
      - wind_speed
      - pressure
      - wind_bearing
      - apparent_temperature
      - icon
      - precip_probability
      - precip_intensity
      - cloud_cover

# Next Sunrise/Sunset Times
  - platform: template
    sensors:
      sunset_time:
        value_template: '{% set timestamp = as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%I:%M %p") %} {{ timestamp.lstrip("0") }}'
        friendly_name: "Sunset"

  - platform: template
    sensors:
      sunrise_time:
        value_template: '{% set timestamp = as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%I:%M %p") %} {{ timestamp.lstrip("0") }}'
        friendly_name: "Sunrise"

  - platform: template
    sensors:
      solar_angle:
        friendly_name: "Sun angle"
        unit_of_measurement: 'degrees'
        value_template: "{{ states.sun.sun.attributes.elevation }}"

# Pi-Hole
  - platform: pi_hole
    host: !secret pi_hole_ip
    monitored_conditions:
      - dns_queries_today
      - ads_blocked_today
      - ads_percentage_today

# Gets public IP
  - platform: dnsip
    scan_interval: 1800

# Harmony Status
  - platform: template
    sensors:
      harmony_living_room:
        value_template: '{{states.remote.living_room.attributes.current_activity }}'
        friendly_name: 'Living Room'

# SABnzbd
  - platform: sabnzbd
    host: !secret sabnzbd_ip
    port: !secret sabnzbd_port
    api_key: !secret sabnzbd_api
    monitored_variables:
      - 'current_status'
      - 'speed'
      - 'queue_size'
      - 'queue_remaining'
      - 'disk_size'
      - 'disk_free'

# Vera Home mode
  - platform: rest
    name: "House Mode"
    resource: !secret hmode_url

  - platform: template
    sensors:
      homemode:
        friendly_name: 'House Mode'
        value_template:  >-
            {%- if is_state("sensor.house_mode", "1") %}
              Home
            {% elif is_state("sensor.house_mode", "2") %}
              Away
            {% elif is_state("sensor.house_mode", "3") %}
              Night
            {% elif is_state("sensor.house_mode", "4") %}
              Vacation
            {%- endif %}

binary_sensor:


##########################################
# Remote
##########################################

remote:

# Harmony Remote
  - platform: harmony
    name: Living Room
    host: !secret livingroom_harmony_ip

##########################################
# Telegram Bot
##########################################

telegram_bot:
  platform: polling
  api_key:  !secret telegram_bot_api_key
  allowed_chat_ids:
    - !secret e_chat_id
    - !secret v_chat_id

#########################################
# Notifications
#########################################

notify:
  - name: telegram_e
    platform: telegram
    chat_id: !secret e_chat_id
  - name: telegram_v
    platform: telegram
    chat_id: !secret v_chat_id
#  - name: notify_chrome
#    platform: html5
#    gcm_api_key: !secret gcm_sender_key
#    gcm_sender_id: !secret gcm_sender_id
    
#########################################
# Zones
#########################################

zone:
  name: !secret e_work_name
  latitude: !secret e_work_lat
  longitude: !secret e_work_long
  radius: 200
  icon: mdi:company

zone 2:
  name: !secret v_work_name
  latitude: !secret v_work_lat
  longitude: !secret v_work_long
  radius: 200
  icon: mdi:cart

#########################################
# iframes
#########################################
panel_iframe:
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:floor-plan
    url_path: floorplan
    config: !include floorplan.yaml

#########################################
# Shell Commands
#########################################

shell_command:
  br_lightsoff: !secret brlightsoff_url
  vera_mode_home: !secret homemode_url
  vera_mode_night: !secret nightmode_url
#  camera_default: !secret camdef_url
#  camera_privacy: !secret campri_url
  bdcam_def: !secret bdcam_def_url
  bdcam_priv: !secret bdcam_priv_url
  party_play: 'curl -g "http://192.168.1.210:8080/jsonrpc?request={"jsonrpc":"2.0","id":"1","method":"Player.Open","params":{"item":{"file":"special://profile/playlists/music/Party.m3u"}}}"'

#########################################
# REST Commands
#########################################

rest_command:
  party_playlist:
    url: 'http://192.168.1.210:8080/jsonrpc?request={"jsonrpc":"2.0","id":"1","method":"Player.Open","params":{"item":{"file":"special://profile/playlists/music/Party.m3u"}}}'

#########################################
# Emulated Hue Bridge
#########################################

emulated_hue:
  type: alexa
  expose_by_default: false

#########################################
# USPS
#########################################

#usps:
#  username: !secret usps_username
#  password: !secret usps_password

#########################################
# Input Selects
#########################################

input_select:

# Harmony Control
  living_room_tv:
    name: Living Room TV
    options:
      - Select Activity
      - Watch TV
      - Watch Kodi
      - Listen to Music
      - Chromecast
      - WiiU
      - Steam Link
      - Power Off
    initial: Select Activity
    icon: mdi:monitor

# Chromecast Radio
  radio_station:
    name: 'Select Radio Station:'
    options:
      - JEMP
      - GD Radio
      - Nugs Radio
      - Hot 97
  chromecast_radio:
    name: 'Select Speakers:'
    options:
      - Living Room
      - Man Cave
      - All
    initial: All
    icon: mdi:speaker-wireless


input_number: 
  volume_radio:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05

#########################################
# Includes
#########################################
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
