homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include custom.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Logging options, and kills Denon errors
logger:
  default: error
#  default: info
  logs:
    DenonAVR: fatal
    homeassistant.components.telegram_bot: info
    homeassistant.components.telegram: info
    homeassistant.components.sabnzbd: info

http:
  api_password: !secret http_pass
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url
  server_port: 8254 
#  ssl_certificate: !secret ssl_fullchain
#  ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Text to speech
tts:
  platform: google

# Track sun
sun:

# Enable MQTT
mqtt:
  broker: !secret mqtt_ip
  port: 8883
  username: !secret mqtt_user
  password: !secret mqtt_password
#  certificate: /etc/mosquitto/certs/ca.crt
  certificate: /etc/ssl/certs/ca-certificates.crt
#  tls_insecure: true
#  protocol: 3.1

# Device Tracker
device_tracker:
  - platform: tplink
    host: !secret router_ip
    username: !secret router_username
    password: !secret router_password
    track_new_devices: false
  - platform: owntracks
    max_gps_accuracy: 200

##########################################
# Lights
##########################################

# Desk LEDs
light:
  - platform: flux_led
    devices:
      192.168.1.103:
        name: mancave_desk
        mode: rgb

##########################################
# Vera
##########################################

vera:
  vera_controller_url: !secret vera_ip
  exclude: [ 166, 152, 144]
  lights: [ 118, 123, 115, 135, 133, 103, 104, 170, 160, 107, 120, 108]

##########################################
# Media Players
##########################################
 
media_player:

# Living Room Kodi
  - platform: kodi
    host: !secret kodi1_ip
    port: 8080
    name: Living Room Kodi
    username: !secret kodi1_user
    password: !secret kodi1_pass

# Bedroom Kodi
  - platform: kodi
    host: !secret kodi2_ip
    port: 8080
    name: Bedroom Kodi

# Denon Receiver
  - platform: denonavr
    host: !secret denonavr_ip

##########################################
# Cams
##########################################

camera:

# Back Door Cam
  - platform: mjpeg
    mjpeg_url: !secret bdcam_url
    name: Back Door
    username: !secret bdcam_user
    password: !secret bdcam_pass

# Front Door Cam
  - platform: mjpeg
    mjpeg_url: !secret fdcam_url
    name: Front Door
    username: !secret fdcam_user
    password: !secret fdcam_pass

# Man Cave Cam
  - platform: mjpeg
    mjpeg_url: !secret mccam_url
    name: Man Cave Camera
    username: !secret mccam_user
    password: !secret mccam_pass

#### Not actual cams, but images to use in HA

# RDU Radar image

  - platform: generic
    still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=RAX&brand=wui&num=1&delay=15&type=N0R&frame=0&scale=1.000&noclutter=1&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=0&lightning=1&smooth=0&rand=24947440&lat=35.59000015&lon=-78.77999878&label=Fuquay-Varina%2C+NC
    name: Radar

# Solar alerts

  - platform: generic
    still_image_url: http://www.n3kl.org/sun/images/status.gif
    name: Solar X-Rays

  - platform: generic
    still_image_url: http://www.n3kl.org/sun/images/kpstatus.gif
    name: Geomagnetic Field
    

##########################################
# Sensors
##########################################

sensor:

# Weather Underground
  - platform: wunderground
    api_key: !secret wu_api
    monitored_conditions:
      - weather_1d
      - weather_1n
      - weather_2d
      - weather_2n
      - weather_3d
      - weather_3n
      - weather_4d
      - weather_4n
      - temp_high_record_f
      - temp_high_1d_f
      - temp_f
      - temp_low_1d_f
      - temp_low_record_f
      - precip_1d
      - precip_1d_in
      - wind_mph
      - wind_1d_mph
      - alerts

# Dark Sky
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - precip_probability
      - precip_intensity

# Next Sunrise/Sunset Times
  - platform: template
    sensors:
      sunset_time:
        value_template: '{% set timestamp = as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%I:%M %p") %} {{ timestamp.lstrip("0") }}'
        friendly_name: "Sunset"

  - platform: template
    sensors:
      sunrise_time:
        value_template: '{% set timestamp = as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%I:%M %p") %} {{ timestamp.lstrip("0") }}'
        friendly_name: "Sunrise"

# Pi-Hole
  - platform: pi_hole
    host: !secret pi_hole_ip
    monitored_conditions:
      - dns_queries_today
      - ads_blocked_today
      - ads_percentage_today

# Gets public IP
  - platform: dnsip
    scan_interval: 1800

# Harmony Status
  - platform: template
    sensors:
      harmony_living_room:
        value_template: '{{states.remote.living_room.attributes.current_activity }}'
        friendly_name: 'Living Room'

# SABnzbd - not working
  - platform: sabnzbd
    host: !secret sabnzbd_ip
    port: !secret sabnzbd_port
    api_key: !secret sabnzbd_api
    monitored_variables:
      - 'current_status'
      - 'speed'
      - 'queue_size'
      - 'queue_remaining'
      - 'disk_size'
      - 'disk_free'

# CoinMarketCap
  - platform: coinmarketcap
    currency: ethereum
# Bitcoin
  - platform: bitcoin
    display_options:
      - exchangerate

binary_sensor:

# Detect ISS position
  - platform: iss
    name: ISS

##########################################
# Remote
##########################################

remote:

# Harmony Remote
  - platform: harmony
    name: Living Room
    host: !secret livingroom_harmony_ip

##########################################
# Telegram Bot
##########################################

telegram_bot:
  platform: polling
  api_key:  !secret telegram_bot_api_key
  allowed_chat_ids:
    - !secret e_chat_id

notify:
  - name: telegram_e
    platform: telegram
    chat_id: !secret e_chat_id
    
#########################################
# Zones
#########################################
zone:
  name: !secret e_work_name
  latitude: !secret e_work_lat
  longitude: !secret e_work_long
  radius: 200
  icon: mdi:company

zone 2:
  name: !secret v_work_name
  latitude: !secret v_work_lat
  longitude: !secret v_work_long
  radius: 200
  icon: mdi:cart

#########################################
# MDI Index
#########################################
panel_iframe:
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html


#########################################
# Includes
#########################################

group: !include groups.yaml
automation: !include automations.yaml

