custom_header:
  compact_mode: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color
title: Cameras
views:
  - title: Cameras
    cards:
      - type: picture-entity
        entity: camera.front_door
        camera_view: live
        show_state: false
      - type: picture-entity
        entity: camera.back_door
        camera_view: live
        show_state: false
      - type: picture-entity
        entity: camera.man_cave_camera
        camera_view: live
        show_state: false
      - type: picture-entity
        entity: camera.deck_cam
        camera_view: live
        show_state: false
