custom_header:
  compact_mode: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)
  header_text: "Casa De Slacktish - Overview"

views:
  - title: Floorplan
    icon: mdi:floor-plan
    path: floorplan
    panel: true
    cards:
      - type: picture-elements
        image: /local/floorplan-wide.png
        style: |
          ha-card {
            background: none;
            box-shadow: none;
            background-color: rgb(9, 9, 9)
          }
        elements:

#################################
# Left Side
#################################

          - type: state-label
            entity: sensor.homemode
            prefix: "Mode: "
            style:
              top: 3%
              left: 3%
              font-size: 2.5em
              #color: darkgreen
              transform: none

          - type: service-button
            title: Home Mode
            service: scene.turn_on
            service_data:
              entity_id: scene.switch_to_home
            style:
              top: 11%
              left: 5%
              transform: none
              color: darkgreen
              border: 2px solid darkgreen
              margin-left: 5px
              font-size: 2em
              font-weight: bold
              padding: 5px
              width: 125px
              text-align: center

          - type: service-button
            title: Night Mode
            service: scene.turn_on
            service_data:
              entity_id: scene.switch_to_night
            style:
              top: 20%
              left: 5%
              transform: none
              color: darkgreen
              border: 2px solid darkviolet
              margin-left: 5px
              font-size: 2em
              font-weight: bold
              padding: 5px
              width: 125px
              text-align: center


#################################
# Weather Section
#################################
          - type: state-label
            entity: weather.weather
            style:
              top: 8%
              left: 40%
              font-size: 1.5em
              transform: none

          - type: state-label
            entity: sensor.wupws_temp
            style:
              top: 5%
              left: 40%
              font-size: 1.5em
              text-align: left
              transform: none

          - type: state-label
            entity: sensor.wupws_heatindex
            prefix: "Heat Index: "
            style:
              top: 11%
              left: 40%
              font-size: 1.5em
              transform: none

          - type: state-label
            entity: sensor.wupws_humidity
            prefix: "Humidity: "
            style:
              top: 14%
              left: 40%
              transform: none

          - type: state-label
            entity: sensor.wupws_windspeed
            prefix: "Wind Speed: "
            style:
              top: 17%
              left: 40%
              transform: none

#################################
# Icons on the floor plan
#################################

# LIVING AREA

          - type: state-icon
            tap_action:
              action: toggle
            entity: light.lamp_107
            style:
              top: 47%
              left: 69%

          - type: state-icon
            tap_action:
              action: toggle
            entity: light.dining_room_lamp_160
            style:
              top: 26%
              left: 87%

          - type: state-icon
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            entity: light.tv
            style:
              top: 32%
              left: 53%

          - type: state-label
            tap_action:
              action: more-info
            entity: sensor.harmony_living_room
            prefix: "Harmony: "
            style:
              top: 27%
              left: 61%

          - type: state-label
            entity: sensor.current_temperature
            style:
              top: 40%
              left: 55%
              font-size: 1.5em
              transform: none

          - type: state-icon
            entity: binary_sensor.smoke_sensor_197
            style:
              top: 32%
              left: 57%

          - type: state-icon
            entity: binary_sensor.co_sensor_198
            style:
              top: 35%
              left: 57%

          - type: state-icon
            tap_action:
              action: toggle
            entity: switch.couch_lights_185
            style:
              top: 40%
              left: 64.5%
          - type: state-icon
            tap_action:
              action: toggle
            entity: switch.music_lights_186
            style:
              top: 43%
              left: 64.5%

# KITCHEN

          - type: state-icon
            tap_action:
              action: toggle
            entity: switch.kitchen_light_183
            style:
              top: 50%
              left: 82.5%

          - type: state-icon
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            entity: light.cabinets
            style:
              top: 59%
              left: 87%

# MASTER

          - type: state-icon
            tap_action:
              action: toggle
            entity: light.bedroom_eric_103
            style:
              top: 26%
              left: 34.5%

          - type: state-icon
            tap_action:
              action: toggle
            entity: light.bedroom_val_104
            style:
              top: 41%
              left: 34.5%

          - type: state-icon
            tap_action:
              action: toggle
            entity: light.vanity_211
            style:
              top: 61%
              left: 43%

          - type: state-icon
            tap_action:
              action: toggle
            entity: switch.master_bath_fan_212
            style:
              top: 61%
              left: 40%

          - type: state-icon
            tap_action:
              action: toggle
            entity: light.master_closet
            style:
              top: 51%
              left: 46%

          - type: state-label
            entity: sensor.masterbath_temperature
            style:
              top: 55%
              left: 39.5%
          - type: state-label
            entity: sensor.humidity_sensor_209
            style:
              top: 57%
              left: 39.5%

# MAN CAVE

          - type: state-icon
            tap_action:
              action: toggle
            entity: switch.man_cave_lights_133
            style:
              top: 82%
              left: 73%

          - type: state-icon
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            entity: light.mancave_desk
            style:
              top: 81%
              left: 60%

          - type: state-icon
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            entity: light.pin_board
            style:
              top: 84%
              left: 60%

          - type: state-icon
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            entity: light.wifi_box
            style:
              top: 87%
              left: 60%

          - type: state-icon
            tap_action:
              action: toggle
            entity: switch.air_purifier
            style:
              top: 87%
              left: 66%

# EXT LIGHTS

          - type: state-icon
            tap_action:
              action: toggle
            entity: switch.front_spotlight_135
            style:
              top: 67%
              left: 34%

          - type: state-icon
            tap_action:
              action: toggle
            entity: switch.front_porch_115
            style:
              top: 60%
              left: 50%

          - type: state-icon
            tap_action:
              action: toggle
            entity: switch.back_spotlight_118
            style:
              top: 21%
              left: 93%

          - type: state-icon
            tap_action:
              action: toggle
            entity: switch.deck_lights_108
            style:
              top: 7.5%
              left: 82%

# DOOR/MOTION SENSORS
          - type: state-icon
            entity: binary_sensor.back_door_172
            style:
              top: 26%
              left: 71%

          - type: state-icon
            entity: binary_sensor.front_door1_1_139
            style:
              top: 54%
              left: 54%

          - type: state-icon
            entity: binary_sensor.motion_sensor_128
            style:
              top: 85%
              left: 73%

          - type: state-icon
            entity: binary_sensor.master_bath_sensor_121
            style:
              top: 53%
              left: 39.5%

          - type: state-icon
            entity: binary_sensor.closet_door_210
            style:
              top: 43.5%
              left: 46%




# CAMS
          - type: state-icon
            tap_action:
              action: more-info
            entity: camera.back_door
            style:
              top: 40%
              left: 77%

          - type: state-icon
            tap_action:
              action: more-info
            entity: camera.deck_cam
            style:
              top: 23%
              left: 77%

          - type: state-icon
            tap_action:
              action: more-info
            entity: camera.front_door
            style:
              top: 47%
              left: 54%

          - type: state-icon
            tap_action:
              action: more-info
            entity: camera.man_cave_camera
            style:
              top: 93%
              left: 66%
