custom_header:
  compact_mode: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)

title: Party/LED Control

views:
  - title: LED Control
    cards:
      - type: custom:stack-in-card
        keep:
          background: true
          margin: true
          border_radius: true
          
        cards:
          - type: custom:button-card
            template: link_buttons
            name: "Switches >"
            icon: mdi:light-switch
            color: white
            tap_action:
              action: navigate
              navigation_path: /lovelace/switches
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                entity: light.mantle
                name: Mantle
                template: rgb_light_button
              - type: "custom:button-card"
                entity: light.fireplace
                name: Fireplace
                template: rgb_light_button
              - type: "custom:button-card"
                entity: switch.couch_lights_185
                template: light_switch_button
              - type: "custom:button-card"
                entity: switch.music_lights_186
                template: light_switch_button
              #- type: "custom:button-card"
              #  entity: switch.party_lights_184
              #  template: light_switch_button
              - type: "custom:button-card"
                entity: switch.camera_position
                template: light_switch_button


          - type: custom:fold-entity-row
            head: light.tv
            entities:
              - type: custom:rgb-light-card
                entity: light.tv
                justify: around
                colors:
                  - rgb_color: [0,0,0]
                    brightness: 15
                    white_value: 30
                    icon_color: white
                  - rgb_color: [0,0,255]
                    brightness: 45
                    white_value: 0
                    icon_color: blue
                  - rgb_color: [255,0,0]
                    brightness: 45
                    white_value: 0
                    icon_color: red
                  - rgb_color: [0,255,00]
                    brightness: 45
                    white_value: 0
                    icon_color: green
                  - icon_color: 'linear-gradient(to right, orange , yellow, green, cyan, blue, violet)'
                    effect: custom
                  - icon_color: 'linear-gradient(to right, red, green, blue)'
                    effect: colorloop
              - sensor.tv_effect
          


#
# LEDfx Section
#

      - type: custom:stack-in-card
        keep:
          background: true
          margin: true
          border_radius: true
        cards:
          - type: custom:button-card
            template: link_buttons
            name: 'LEDfx Dashboard >'
            entity_picture: /local/ledfx.png
            show_entity_picture: true
            tap_action:
              action: url
              url_path: "http://192.168.1.10:8888/dashboard"
          - type: horizontal-stack
            #title: LEDfx
            cards:
              - type: "custom:button-card"
                entity: script.ledfx_wled1_wave
                name: Wave
                icon: mdi:numeric-1-box-multiple-outline
                template: script_buttons
              - type: "custom:button-card"
                entity: script.ledfx_waverain
                name: WaveRain
                icon: mdi:numeric-2-box-multiple-outline
                template: script_buttons

          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                entity: script.ledfx_all_off
                name: LEDfx Off
                icon: mdi:led-variant-off
                template: script_buttons
                aspect_ratio: 6/1
          
#
# WLED Section
#

      - type: custom:stack-in-card
        keep:
          background: true
          margin: true
          border_radius: true
        cards:
          - type: custom:light-entity-card
            entity: light.wled1
            persist_features: true
            show_slider_percent: true
            group: true
            shorten_cards: true
            effects_list: false
          - type: custom:button-card
            template: wled_button
            entity: light.wled1
          - type: custom:light-entity-card
            entity: light.mantle
            persist_features: true
            show_slider_percent: true
            group: true
            shorten_cards: true
            effects_list: false
          - type: custom:button-card
            template: wled_button
            entity: light.mantle
      - type: custom:stack-in-card
        keep:
          background: true
          margin: true
          border_radius: true
        cards:   
          - type: custom:light-entity-card
            entity: light.desk
            persist_features: true
            show_slider_percent: true
            group: true
            shorten_cards: true
            effects_list: false
          - type: custom:button-card
            template: wled_button
            entity: light.desk
          - type: custom:light-entity-card
            entity: light.front_porch_leds
            persist_features: true
            show_slider_percent: true
            group: true
            shorten_cards: true
            effects_list: false
          - type: custom:button-card
            template: wled_button
            entity: light.front_porch_leds

# Templates for button-card
button_card_templates:
  !include button-card-templates.yaml
