title: Party/LED Control
views:
  - title: LED Control
    cards:
##########################################
# Switches
##########################################       
      - type: custom:stack-in-card
        keep:
          background: true
          margin: true
          border_radius: true
        cards:
          - type: custom:button-card
            template: link_buttons
            name: "Switches >"
            icon: mdi:light-switch
            color: white
            tap_action:
              action: navigate
              navigation_path: /lovelace/switches
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                entity: light.lamp_107
                name: Living Lamp
                template: light_button_brightness

              - type: "custom:button-card"
                entity: light.tv
                name: TV
                template: rgb_light_button

              - type: "custom:button-card"
                entity: light.dining_room_lamp_160
                name: Dining Lamp
                template: light_button_brightness
              
              - type: "custom:button-card"
                entity: light.dining_shelf
                name: Dining Shelf
                template: rgb_light_button
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                entity: light.mantle
                name: Mantle
                template: rgb_light_button
              - type: "custom:button-card"
                entity: light.fireplace
                name: Fireplace
                template: rgb_light_button
              - type: "custom:button-card"
                entity: switch.aoycocr_plug_2
                template: light_switch_button
                name: Black Light
              - type: "custom:button-card"
                entity: switch.aoycocr_plug_1
                template: light_switch_button
              
              
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                entity: light.clock
                name: Clock
                template: rgb_light_button
              - type: "custom:button-card"
                entity: switch.couch_lights_185
                template: light_switch_button
              - type: "custom:button-card"
                entity: switch.music_lights_186
                template: light_switch_button
              
              - type: "custom:button-card"
                entity: switch.camera_position
                template: light_switch_button
              

          - type: custom:fold-entity-row
            head: light.tv
            entities:
              - type: custom:rgb-light-card
                entity: light.tv
                justify: around
                colors:
                  - rgb_color: [0,0,0]
                    brightness: 15
                    white_value: 30
                    icon_color: white
                  - rgb_color: [0,0,255]
                    brightness: 45
                    white_value: 0
                    icon_color: blue
                  - rgb_color: [255,0,0]
                    brightness: 45
                    white_value: 0
                    icon_color: red
                  - rgb_color: [0,255,00]
                    brightness: 45
                    white_value: 0
                    icon_color: green
                  - icon_color: 'linear-gradient(to right, orange , yellow, green, cyan, blue, violet)'
                    effect: custom
                  - icon_color: 'linear-gradient(to right, red, green, blue)'
                    effect: colorloop
              - sensor.tv_effect

##########################################
# LEDfx Section
##########################################

      - type: custom:stack-in-card
        keep:
          background: true
          margin: true
          border_radius: true
        cards:
          - type: custom:button-card
            template: link_buttons
            name: 'LEDfx Dashboard >'
            entity_picture: /local/ledfx.png
            show_entity_picture: true
            tap_action:
              action: url
              url_path: "http://192.168.1.10:8888/dashboard"
          - type: horizontal-stack
            #title: LEDfx
            cards:
              - type: "custom:button-card"
                entity: script.ledfx_brp
                name: BRP
                icon: mdi:numeric-1-box-multiple-outline
                template: script_buttons
              - type: "custom:button-card"
                entity: script.ledfx_fowlbrp
                name: "BRP+F"
                icon: mdi:numeric-2-box-multiple-outline
                template: script_buttons
              - type: "custom:button-card"
                entity: script.ledfx_plasma
                name: Pl
                icon: mdi:numeric-3-box-multiple-outline
                template: script_buttons
              - type: "custom:button-card"
                entity: script.ledfx_fowlplasma
                name: "Pl+F"
                icon: mdi:numeric-4-box-multiple-outline
                template: script_buttons

          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                entity: script.ledfx_all_off
                name: LEDfx Off
                icon: mdi:led-variant-off
                template: script_buttons
                aspect_ratio: 6/1
          
##########################################
# WLED Section
##########################################
      - type: custom:light-entity-card
        entity: light.ent_cent
        persist_features: true
        show_slider_percent: true
        white_value: false
        color_temp: false
      
      - type: custom:light-entity-card
        entity: light.mantle
        persist_features: true
        show_slider_percent: true
        white_value: false
        color_temp: false

      - type: custom:light-entity-card
        entity: light.clock
        persist_features: true
        show_slider_percent: true
        white_value: false
        color_temp: false
      
      - type: custom:light-entity-card
        entity: light.dining_shelf
        persist_features: true
        show_slider_percent: true
        white_value: false
        color_temp: false
      
      - type: custom:light-entity-card
        entity: light.desk
        persist_features: true
        show_slider_percent: true
        white_value: false
        color_temp: false
      
      - type: custom:light-entity-card
        entity: light.front_porch_leds
        persist_features: true
        show_slider_percent: true
        white_value: false
        color_temp: false


      - type: custom:light-entity-card
        entity: light.goose
        persist_features: true
        show_slider_percent: true
        white_value: false
        color_temp: false

      # - type: custom:stack-in-card
      #   cards:
      #     - type: custom:fold-entity-row
      #       head: light.ent_cent
      #       entities:
      #         - type: custom:rgb-light-card
      #           entity: light.ent_cent
      #           colors:
      #             - type: call-service
      #               service: rest_command.wled1_xmas
      #               icon_color: 'linear-gradient(90deg, red,  green)'
      #               label: Xmas
              
      #     - type: custom:fold-entity-row
      #       head: light.mantle
      #       entities:
      #         - type: custom:rgb-light-card
      #           entity: light.mantle
      #           colors:
      #             - type: call-service
      #               service: rest_command.mantle_solid
      #               icon_color: green
      #               label: Solid
      #             - type: call-service
      #               service: rest_command.mantle_wipe
      #               icon_color: 'linear-gradient(to right, red, green, blue, green, red)'
      #               label: Wipe
      #             - type: call-service
      #               service: rest_command.mantle_xmas
      #               icon_color: 'linear-gradient(90deg, red,  green)'
      #               label: Xmas
                  
      #     - type: custom:fold-entity-row
      #       head: light.dining_shelf
      #       entities:
      #         - type: custom:rgb-light-card
      #           entity: light.dining_shelf
      #           colors:
      #             - type: call-service
      #               service: rest_command.diningshelf_solid
      #               icon_color: blue
      #               label: Solid
      #             - type: call-service
      #               service: rest_command.diningshelf_glitter
      #               icon_color: 'linear-gradient(to right, orange , yellow, green, cyan, blue, violet)'
      #               label: Glitter
      #             - type: call-service
      #               service: rest_command.diningshelf_xmas
      #               icon_color: 'linear-gradient(to right, red, green)'
      #               label: Xmas


# Templates for button-card
button_card_templates:
  !include button-card-templates.yaml
