custom_header:
  compact_mode: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color
title: System
views:
  - title: System
    icon: mdi:home-assistant
    cards:
  
  # System info and commands
      - type: custom:stack-in-card
        keep:
          background: true
        cards:
          - type: custom:button-card
            name: "Hass/System"
            template: general_label
          - type: custom:button-card
            entity: sensor.current_version
            name: HASS
            show_state: false
            show_name: false
            show_label: false
            show_icon: false
            styles:
              grid:
                - grid-template-areas: '"cv av hacs" "up log boot"' 
                - grid-template-columns: 1fr 1fr 1fr
                - grid-template-rows: min-content min-content
              
              state:
                - align-self: middle
                - justify-self: center
              custom_fields:
                cv:
                  - align-self: middle
                  - justify-self: center
                  - font-size: 14px
                  - padding-bottom: 10px
                av:
                  - align-self: middle
                  - justify-self: center
                  - font-size: 14px
                  - padding-bottom: 10px
                hacs:
                  - align-self: middle
                  - justify-self: center
                  - font-size: 14px
                  - padding-bottom: 10px
                up:
                  - align-self: middle
                  - justify-self: center
                  - font-size: 14px
                log:
                  - align-self: middle
                  - justify-self: center
                  - font-size: 14px
                boot:
                  - align-self: middle
                  - justify-self: center
                  - font-size: 14px
            custom_fields:
              cv: >
                [[[ return `
                  <span>Running:<br>${states['sensor.current_version'].state}</span>`
                ]]]
              av: >
                [[[ return `
                  <span>Available:<br>${states['sensor.hass_avail_version'].state}</span>`
                ]]]
              hacs: >
                [[[ return `
                  <span>HACS:<br>${states['sensor.hacs'].state} updates</span>`
                ]]]
              up: >
                [[[ return `
                  <span>HASS Last Boot:<br>${states['sensor.hass_uptime'].state}</span>`
                ]]]
              log: >
                [[[ return `
                  <span>Last Login:<br>${states['sensor.last_successful_authentication'].state}</span>`
                ]]]
              boot: >
                [[[ return `
                  <span>Server Last Boot:<br>${states['sensor.server_uptime'].state}</span>`
                ]]]

          - type: custom:stack-in-card
            mode: horizontal
            keep:
              margin: true
              border_radius: true
            cards:
              - type: "custom:mini-graph-card"
                entities:
                  - sensor.processor_use
                name: "CPU"
                align_icon: left
                align_state: center
                font_size: 75
                show:
                  fill: false
              - type: "custom:mini-graph-card"
                entities:
                  - sensor.memory_use_percent
                name: "RAM"
                align_icon: left
                align_state: center
                font_size: 75
                show:
                  fill: false
              - type: "custom:mini-graph-card"
                entities:
                  - sensor.disk_use_percent_home
                name: "Disk"
                align_icon: left
                align_state: center
                font_size: 75
                show:
                  fill: false

          - type: custom:stack-in-card
            mode: horizontal
            keep:
              margin: true
              border_radius: true
              background: true
            cards:
              - type: custom:button-card
                icon: mdi:reload
                name: Restart Vera
                entity: scene.reboot_vera
                template: system_button
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  entity: scene.reboot_vera
              - type: "custom:button-card"
                color_type: blank-card
                color_off: var(--disabled-text-color)
              - type: "custom:button-card"
                color_type: blank-card
                color_off: var(--disabled-text-color)
              - type: "custom:button-card"
                color_type: blank-card
                color_off: var(--disabled-text-color)
  # Network Info
      - type: custom:stack-in-card
        keep:
          background: true
        cards:
          - type: custom:button-card
            name: Network
            template: general_label
          - type: entities
            entities:
              - sensor.myip
              - sensor.ipv4_address_ens160
              - sensor.cert_exp_date
          - type: "custom:mini-graph-card"
            entities:
              - entity: sensor.network_throughput_in_ens160
                name: "Net In (MB/s)"
              - entity: sensor.network_throughput_out_ens160
                name: "Net Out (MB/s)"
                color: green
            name: "Network"
            align_icon: left
            font_size: 75
            line_width: 2
            hours_to_show: 24
            points_per_hour: 15
            show:
              fill: false
              state: false
              extrema: true
          - type: custom:mini-graph-card
            name: Pi-Hole
            show:
              state: false
              fill: false
              smoothing: false
              graph: bar
            line_width: 2
            entities:
              - entity: sensor.pi_hole_dns_queries_today
                name: Queries Today
                
              - entity: sensor.pi_hole_ads_blocked_today
                name: Ads Blocked Today
                color: orange
            hours_to_show: 168
            points_per_hour: .0416
            group_by: day

          - type: entities
            entities:
              - sensor.pi_hole_ads_percentage_blocked_today
              - sensor.pi_hole_ads_blocked_today
              - sensor.pi_hole_dns_queries_today
              - sensor.pi_hole_dns_queries_cached
              - sensor.pi_hole_dns_queries_forwarded
              - sensor.pi_hole_dns_unique_clients
              - sensor.pi_hole_seen_clients
              - sensor.pi_hole_dns_unique_domains
              - sensor.pi_hole_domains_blocked
  # Battery Levels
      - type: custom:stack-in-card
        keep:
          background: true
        cards:
          - type: custom:button-card
            name: Batteries
            template: general_label
          - type: custom:auto-entities
            card:
              type: custom:bar-card
              attribute: battery_level
              severity:
                - from: 0
                  to: 50
                  color: 'rgba(191, 64, 64, 0.5)'
                - from: 51
                  to: 75
                  color: 'rgba(191, 149, 64, 0.5)'
                - from: 76
                  to: 100
                  color: 'rgba(64, 191, 64, 0.5)'
              columns: 2

            filter:
              include:
                - attributes:
                    battery_level: <=100
  # HASS Toggles and inputs
      - type: custom:stack-in-card
        keep:
          background: true
        cards:
          - type: custom:button-card
            name: Options
            template: general_label
          - type: entities
            entities: 
              - type: section
                label: "System-wide Options"
              - entity: input_boolean.wfh
                name: "WFH Mode Enabled"
              - entity: input_boolean.holiday_exterior
                name: "Holiday Mode: Exterior"
              - entity: input_boolean.holiday_interior
                name: "Holiday Mode: Interior"
              - type: section
                label: "Lights"
              - type: custom:numberbox-card
                entity: input_number.int_sa
                name: "Int Lights - Solar Angle"
                speed: 0
                border: false
              - type: custom:numberbox-card
                entity: input_number.ext_sa
                name: "Ext Lights - Solar Angle"
                speed: 0
                border: false
  

# Templates for button-card
button_card_templates:
  !include button-card-templates.yaml
