custom_header:
  compact_mode: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color
title: System
views:
  - title: System
    icon: mdi:home-assistant
    cards:
  # Network Info
      - type: custom:stack-in-card
        keep:
          background: true
        cards:
          - type: custom:button-card
            name: Network
            template: general_label
          - type: custom:stack-in-card
            mode: horizontal
            keep:
              margin: true
              border_radius: true
              background: true
            cards:
              - type: custom:button-card
                name: "Public IP:"
                entity_picture: /local/network.jpg
                entity: sensor.myip
                icon: mdi:router-network
                show_state: true
                show_icon: true
                show_entity_picture: false
                show_last_changed: true
                size: 64px
                layout: icon_name_state2nd
              - type: custom:button-card
                name: "SSL Cert Expiry:"
                entity: sensor.ssl_certificate_expiry
                show_state: true
                show_icon: true
                size: 64px
                layout: icon_name_state2nd
                tap_action:
                  action: url
                  url_path: https://evilrobot.space
                styles:
                  icon:
                    - color: >
                        [[[
                          if (entity.state > 60) return 'lime';
                          if (entity.state <= 60 && entity.state >= 30) return 'orange';
                          else return 'darkred';
                        ]]]
  # System info and commands
      - type: custom:stack-in-card
        keep:
          background: true
        cards:
          - type: custom:button-card
            name: "Hass/System"
            template: general_label
          - type: custom:button-card
            entity: sensor.current_version
            name: HASS
            show_state: false
            show_name: false
            show_label: false
            show_icon: false
            styles:
              grid:
                - grid-template-areas: '"cv av hacs" "up log boot"' 
                - grid-template-columns: 1fr 1fr 1fr
                - grid-template-rows: min-content min-content
              
              state:
                - align-self: middle
                - justify-self: center
              custom_fields:
                cv:
                  - align-self: middle
                  - justify-self: center
                  - font-size: 14px
                  - padding-bottom: 10px
                av:
                  - align-self: middle
                  - justify-self: center
                  - font-size: 14px
                  - padding-bottom: 10px
                hacs:
                  - align-self: middle
                  - justify-self: center
                  - font-size: 14px
                  - padding-bottom: 10px
                up:
                  - align-self: middle
                  - justify-self: center
                  - font-size: 14px
                log:
                  - align-self: middle
                  - justify-self: center
                  - font-size: 14px
                boot:
                  - align-self: middle
                  - justify-self: center
                  - font-size: 14px
            custom_fields:
              cv: >
                [[[ return `
                  <span>Running:<br>${states['sensor.current_version'].state}</span>`
                ]]]
              av: >
                [[[ return `
                  <span>Available:<br>${states['sensor.hass_avail_version'].state}</span>`
                ]]]
              hacs: >
                [[[ return `
                  <span>HACS:<br>${states['sensor.hacs'].state} updates</span>`
                ]]]
              up: >
                [[[ return `
                  <span>HASS Uptime:<br>${states['sensor.uptime'].state} Hours</span>`
                ]]]
              log: >
                [[[ return `
                  <span>Last Login:<br>${states['sensor.last_successful_authentication'].state}</span>`
                ]]]
              boot: >
                [[[ return `
                  <span>Server Last Boot:<br>${states['sensor.server_uptime'].state}</span>`
                ]]]

          - type: custom:stack-in-card
            mode: horizontal
            keep:
              margin: true
              border_radius: true
            cards:
              - type: "custom:mini-graph-card"
                entities:
                  - sensor.processor_use
                name: "CPU"
                align_icon: left
                align_state: center
                font_size: 75
                show:
                  fill: false
              - type: "custom:mini-graph-card"
                entities:
                  - sensor.memory_use_percent
                name: "RAM"
                align_icon: left
                align_state: center
                font_size: 75
                show:
                  fill: false
              - type: "custom:mini-graph-card"
                entities:
                  - sensor.disk_use_percent_home
                name: "Disk"
                align_icon: left
                align_state: center
                font_size: 75
                show:
                  fill: false

          - type: custom:stack-in-card
            mode: horizontal
            keep:
              margin: true
              border_radius: true
              background: true
            cards:
              - type: custom:button-card
                icon: mdi:reload
                name: Restart Vera
                entity: scene.reboot_vera
                template: system_button
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  entity: scene.reboot_vera
              - type: "custom:button-card"
                color_type: blank-card
                color_off: var(--disabled-text-color)
              - type: "custom:button-card"
                color_type: blank-card
                color_off: var(--disabled-text-color)
              - type: "custom:button-card"
                color_type: blank-card
                color_off: var(--disabled-text-color)
  # Battery Levels
      - type: custom:stack-in-card
        keep:
          background: true
        cards:
          - type: custom:button-card
            name: Batteries
            template: general_label
          - type: custom:auto-entities
            card:
              type: custom:bar-card
              attribute: battery_level
              severity:
                - from: 0
                  to: 50
                  color: 'rgba(191, 64, 64, 0.5)'
                - from: 51
                  to: 75
                  color: 'rgba(191, 149, 64, 0.5)'
                - from: 76
                  to: 100
                  color: 'rgba(64, 191, 64, 0.5)'
              columns: 2

            filter:
              include:
                - attributes:
                    battery_level: <=100
# Templates for button-card
button_card_templates:
  !include button-card-templates.yaml
